name: Build Windows EXE

on:
  push:
    branches: [ main ]
    tags: ['v*']     # create a release when tagging like v1.2.3
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # match your project

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (pip)
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # If you use Poetry instead of pip, uncomment this block and remove the pip block above:
      # - name: Install dependencies (Poetry)
      #   run: |
      #     pip install poetry
      #     poetry install --no-interaction --no-root
      #     poetry run pip install pyinstaller

      - name: Build exe with PyInstaller
        shell: bash
        run: |
          # Adjust: your package/module that exposes __main__
          ENTRY="src/app/__main__.py"
          # Common args: --onefile for single exe, --noconsole for GUI apps
          pyinstaller "$ENTRY" \
            --name "MyApp" \
            --onefile \
            --noconsole \
            --clean

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-windows
          path: dist/MyApp.exe
          if-no-files-found: error

  release:
    # Only run when the push is a tag (e.g., v1.2.3)
    needs: build-windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: MyApp-windows
          path: .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: MyApp.exe
